apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: python-flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
        - name: python-flask
          image: linclaus/python-flask:v0.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask
  labels:
    app: python-flask
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
  selector:
    app: python-flask

